Created a harmony-basics tutorial
tr808axm/raftmodding-docs pull request #8
Opened 2020-10-31 00:43 UTC by soggylithe

Created a tutorial with the basics of Harmony consolidated into one place. Should be enough to get someone up and running with no previous knowledge of Harmony or little coding knowledge.

2020-10-31 12:10 UTC, tr808axm requested changes

2020-10-31 12:10 UTC, tr808axm commented on modding-tutorials/harmony-basics.md
> +## Traversing
It looks like something is missing here. Please either delete the heading or add a paragraph.

2020-10-31 12:10 UTC, tr808axm commented on modding-tutorials/harmony-basics.md
> +## Traversing
If you want, you can add your name at the bottom of the tutorial, but you don't need to :)

2020-10-31 12:10 UTC, tr808axm commented on modding-tutorials/harmony-basics.md
> +I'll be honest I don't understand this one and works other than it is a different way to tell Harmony which method you are changing instead of using the class attribute
`[HarmonyTargetMethod]` can be used to dynamically choose a target method. If you can't explain this one, leave it out of the docs.

2020-10-31 12:14 UTC, tr808axm commented
You'll also need to add a link to your tutorial to the `SUMMARY.md` file at the root of this repo. The summary is basically a table of contents for the docs.

2020-10-31 17:14 UTC, soggylithe commented on modding-tutorials/harmony-basics.md
> +    {...}
Do you mean just opening the curly brackets with nothing in them? The indents currently match up with all the other code blocks. Classes are flush, methods are 1tab and nested brackets are inline with contents tabbed up one.

Would this work better:
    [HarmonyPostfix]
    static BuildError CheckForAlt(BuildError __result)
    {
    }

or:
    [HarmonyPostfix]
    static BuildError CheckForAlt(BuildError __result)
    {
        /*Code here*/
    }

2020-10-31 18:25 UTC, tr808axm requested changes

2020-10-31 18:25 UTC, tr808axm commented on modding-tutorials/harmony-basics.md
> +    {...}
Your braces style is fine. What I mean is the fact that the `CheckForAlt` method is indented with spaces and the rest is indented with tabs. Here's a screenshot that demonstrates my point:

![image](https://user-images.githubusercontent.com/10695278/97786816-69e7f200-1bae-11eb-86fa-412ff147f175.png)

2020-11-01 11:22 UTC, tr808axm approved these changes
Looks good!

2020-11-01 11:22 UTC, merged

2020-11-01 11:28 UTC, tr808axm commented
Thanks a lot for your contribution!